server:
  port: 8081

spring:
  application:
    name: consumerOneService

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos服务端地址
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务发现地址
        cluster-name: BeijingCluster #集群名称
        namespace: 3d077be2-bf3b-444c-aa09-4404b0e5f98c #命名空间id

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: 169167866Spl.
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    #控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置feign日志级别
feign:
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    enabled: true  #开启feign对httpclient的支持
    max-connections: 200   #开启最大连接数
    max-connections-per-route: 50  #每个路径最大连接数
