server:
  port: 8083

spring:
  application:
    name: commonFileService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos服务端地址
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务发现地址
        cluster-name: BeijingCluster #集群名称
        namespace: 3d077be2-bf3b-444c-aa09-4404b0e5f98c #命名空间id

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: 169167866Spl.
      driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB   #文件大小设置
      max-request-size: 20MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    #控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件操作相关配置
file:
  basePath: D:\IDMdownload\file  #文件存储的父级目录
  ip: localhost  #存储文件的主机ip