server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848    #注册中心地址
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: BeijingCluster  #集群名称
        namespace: 3d077be2-bf3b-444c-aa09-4404b0e5f98c #命名空间id

    #网关配置
    gateway:
      routes:
        #tagInfo服务
        - id: tagInfo-service   #路由id，自定义，保证唯一即可
          uri: lb://tagInfoService   #服务名
          predicates:       #断言
            - Path=/tagInfo/**   #按照路径匹配，只要以/tagInfo/开头就符合要求
          filters:
            - AddRequestHeader=Truth, add a header!
        #consumerOne服务
        - id: consumerOne-service
          uri: lb://consumerOneService
          predicates:
            - Path=/consumerOne/**
          filters:   #路由过滤器
            - AddRequestHeader=Truth, add a header!

      default-filters:  #默认过滤器，会对所有的路由请求生效
        - AddRequestHeader=name, zhangsan



